name: Benchmark

on:
  pull_request:
  push:

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

        # this is the performance benchmark
      - name: Cache deps
        run: deno cache performance/mod.ts
      - name: Run Benchmark
        run: NO_COLOR=true deno bench --unstable -A performance/mod.ts | tee output.txt
      - name: Format Benchmark Output
        run: deno run -A performance/tranformOutput.ts

        # this is the memory benchmark
      - name: Download db from benchmark repo
        run: wget https://github.com/discordeno/benchmarks/raw/main/db.tar.gz
      - name: Decompress db
        run: tar -xzvf db.tar.gz
      - name: Run memory benchmark
        run: deno run --v8-flags="--expose-gc" -A performance/memory.ts

      - uses: actions/upload-artifact@v3
        with:
          name: benchmarkResults
          path: output.txt

      - name: Create banchies branch
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "banchies"

      - name: Store benchmark result (For Pull Request)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "customSmallerIsBetter"
          output-file-path: output.txt
          gh-pages-branch: "benchies"
          benchmark-data-dir-path: benchmarksResult
          gh-repository: ${{ github.event.pull_request.head.repo.full_name != '' && github.event.pull_request.head.repo.full_name || github.event.push.repository.full_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      - name: Store benchmark result (On main repo)
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: "customSmallerIsBetter"
          output-file-path: output.txt
          gh-pages-branch: "benchies"
          benchmark-data-dir-path: benchmarksResult
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

      - name: Save Commmit SHA
        run: |
          mkdir -p ./commitData
          echo $GITHUB_SHA > ./commitData/sha
          echo $GITHUB_REPOSITORY > ./commitData/repo
      - uses: actions/upload-artifact@v3
        with:
          name: commitData
          path: commitData/
